site_name: Projetos em DS
repo_name: "data-science"
repo_url: "https://github.com/Carolbalbs/data-science"

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

  features:
   - navigation.tabs
  font:
   text: Roboto
   code: Roboto Mono
   size: 10


plugins:
- search:
    separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'


nav:
  - Home: index.md
  - Vm e Postgres: vm-config/req-install.md
  - Dashboards: proj-dash/dash.md
  - Analise de Regressão: proj-reg/analise-reg.md
  - PLN: proj-pln/corretor.md


